### ISSUE TITLE
Integrate with FLTK

### ISSUE THREAD

**Issue by bergwerf** [alexander-dembinsky/cairodart#21]
Hi! I created a VM extension for FLTK: https://pub.dartlang.org/packages/fltk (I'm pretty sure it won't work out of the box, you'll need to compile FLTK etc., but I'm working on that). In case you're not familiar with FLTK, it's a very simple C++ GUI library. FLTK also supports using Cairo for graphics (example: https://github.com/hermanbergwerf/fltk-dart/blob/master/example/cairo.cpp) and I want to use your library to use this in my FLTK Dart port. FLTK gives me a `cairo_t` pointer in the draw function, and I need to convert that into a `Context` from `cairodart`. One way would be to create an `int64_t` from the `cairo_t` pointer address, and use the integer to construct a `Context` (you can cast it back into a pointer). Such a constructor does not currently exists, could you add it?

**Comment by alexdemb** [comment]
Hi! 
Sure, I can provide such ability for you.
I'll notify when changes will be ready for testing.

**Comment by bergwerf** [comment]
Awesome, thanks!

**Comment by alexdemb** [comment]
@hermanbergwerf, changes added to master branch.
Please review linked commit. You are able to create **Context** object (fromNative()) using any instance of **NativeFieldWrapperClass2** where native field at index 0 is a pointer to **cairo_t**.
Note, that cairodart use **provided** pointer, so it will not be responsible for releasing it.

If it works for you, i will make a new release.

Thanks.

**Comment by bergwerf** [comment]
AFAIK you cannot construct a `NativeFieldWrapperClass2` directly (https://github.com/dart-lang/sdk/blob/0c1e85ebadaa0680d4ff30acc1f3ac823c53756e/sdk/lib/html/dartium/nativewrappers.dart#L8). However, I created an empty wrapper and it works anyway. I can successfully pass the context to Dart!

FYI, there is a typo here: https://github.com/alexander-dembinsky/cairodart/blob/2b3114876d92f8aa4d58676bb99903577be386a3/lib/src/context.dart#L41.

Another note: when compiling your library you need to install `qt4-make` and add the Dart SDK include library to `CPATH` (because your build system assumes it's already in there, which is not the case by default, it might be useful to add a heads up to the read me or create a more complete build script).

This is very cool, thanks!

**Comment by bergwerf** [comment]
In case you are curious what it looks like, here is a working example: https://github.com/hermanbergwerf/fltk-dart/blob/1c408eb6dc0d81157a4ccecf94736a8889a3a3cb/test/cairo.dart

And a screenshot:
![screenshot from 2016-08-24 14-06-57](https://cloud.githubusercontent.com/assets/4458965/17930013/6af5a260-6a04-11e6-9374-2701f227529c.png)

Awesome, right ;-)

**Comment by alexdemb** [comment]
Looks great :)

Release 0.2.1 published to pub.dartlang.org. 
It contains changes made under this issue.
