### ISSUE TITLE
Use Uin8List for handle pixel data?

### ISSUE THREAD

**Issue by bergwerf** [alexander-dembinsky/cairodart#22]
I think it is much more elegant to use a `Uint8List` to handle pixel data (`ImageSurface.forData` and `ImageSurface.data`). I'm not sure if it's isolated to these cases. Using `Uint8List` is probably also more efficient.

**Comment by bergwerf** [comment]
Reasons to use `TypedData`:

> For long lists, this implementation can be considerably more space- and time-efficient than the default List implementation.

See: https://api.dartlang.org/stable/1.19.0/dart-typed_data/Uint8List-class.html

**Comment by alexdemb** [comment]
Version **0.2.2** has been published to pub.
It contains this fix.

Thanks.
